fix update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -47,28 +47,28 @@ commands:
   #           aws s3 rm s3://udapeople-<<parameters.workflow_ID>> --recursive
   #           aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_ID >>
 
-  revert-migrations:
-    description: Revert the last migration if successfully run in the current workflow.
-    parameters:
-      workflow_ID:
-        type: string
-        default: ${CIRCLE_WORKFLOW_ID:0:7}
-    steps:
-      - run:
-          name: Revert migrations
-          when: on_fail
-          command: |
-            SUCCESS=$(curl --insecure https://kvdb.io/7K8o6uZo6QoMYXeL9BabiR/migration_<< parameters.workflow_ID >>)
-            #   Description: 
-            #   Type: String|Number|CommaDelimitedList
-            #   Default: -)
-            # SUCCESS = 1
-            if (( $SUCCESS==1 )); 
-            then
-              cd ~/project/backend
-              npm install
+  # revert-migrations:
+  #   description: Revert the last migration if successfully run in the current workflow.
+  #   parameters:
+  #     workflow_ID:
+  #       type: string
+  #       default: ${CIRCLE_WORKFLOW_ID:0:7}
+  #   steps:
+  #     - run:
+  #         name: Revert migrations
+  #         when: on_fail
+  #         command: |
+  #           SUCCESS=$(curl --insecure https://kvdb.io/7K8o6uZo6QoMYXeL9BabiR/migration_<< parameters.workflow_ID >>)
+  #           #   Description: 
+  #           #   Type: String|Number|CommaDelimitedList
+  #           #   Default: -)
+  #           # SUCCESS = 1
+  #           if (( $SUCCESS==1 )); 
+  #           then
+  #             cd ~/project/backend
+  #             npm install
               
-            fi            
+  #           fi            
 jobs:
   build-frontend:
     docker:
@@ -139,9 +139,6 @@ jobs:
             npm install 
             npm test
       # - notify_on_failure
-
-
-            
   scan-frontend:
     docker:
       - image: cimg/node:13.8.0
@@ -158,8 +155,6 @@ jobs:
             #npm audit fix --force --audit-level=critical
             #npm audit --audit-level=critical
       # - notify_on_failure
-
-
   scan-backend:
     docker:
       - image: cimg/node:13.8.0
@@ -213,208 +208,208 @@ jobs:
 
       # - destroy_environment
      
-  configure-infrastructure:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_ansible
-      - add_ssh_keys:
-          fingerprints: ["6a:26:0d:3e:92:ad:4b:a4:b8:c3:19:df:a2:01:1b:71"]
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Configure server
-          command: |
-            ansible-playbook .circleci/ansible/configure-server.yml -i .circleci/ansible/inventory.txt
+  # configure-infrastructure:
+  #   docker:
+  #     - image: cimg/base:stable
+  #   steps:
+  #     - checkout
+  #     - install_awscli
+  #     - install_ansible
+  #     - add_ssh_keys:
+  #         fingerprints: ["6a:26:0d:3e:92:ad:4b:a4:b8:c3:19:df:a2:01:1b:71"]
+  #     - attach_workspace:
+  #         at: ~/
+  #     - run:
+  #         name: Configure server
+  #         command: |
+  #           ansible-playbook .circleci/ansible/configure-server.yml -i .circleci/ansible/inventory.txt
       # - destroy_environment
  
-  run-migrations:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Run migrations
-          command: |
-            cd backend 
-            npm install
-            npm run migrations > migrations_dump.txt
-            cat migrations_dump.txt
-      - run: 
-          name: Send Migration Results to kvdb.io
-          command: |
-            cd backend            
-            if grep -q "has been executed successfully." migrations_dump.txt
-            then
-              echo Send Migration Results to kvdb.io
-              # If you are using kvdb.io, generate the bucket ID "7K8o6uZo6QoMYXeL9BabiR" in your local terminal first
-              curl https://kvdb.io/7K8o6uZo6QoMYXeL9BabiR/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
-            fi
-      # - destroy_environment
-      # - revert-migrations
+#   run-migrations:
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - install_nodejs
+#       - run:
+#           name: Run migrations
+#           command: |
+#             cd backend 
+#             npm install
+#             npm run migrations > migrations_dump.txt
+#             cat migrations_dump.txt
+#       - run: 
+#           name: Send Migration Results to kvdb.io
+#           command: |
+#             cd backend            
+#             if grep -q "has been executed successfully." migrations_dump.txt
+#             then
+#               echo Send Migration Results to kvdb.io
+#               # If you are using kvdb.io, generate the bucket ID "7K8o6uZo6QoMYXeL9BabiR" in your local terminal first
+#               curl https://kvdb.io/7K8o6uZo6QoMYXeL9BabiR/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
+#             fi
+#       # - destroy_environment
+#       # - revert-migrations
 
-#      # Here's where you will add some code to rollback on failure      
+# #      # Here's where you will add some code to rollback on failure      
 
-  deploy-frontend:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run: sudo apt-get install tar gzip -y
-      - restore_cache:
-          keys: [frontend-build]
-      - run:
-          name: Get backend url
-          command: |
-            export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[].Instances[].PublicIpAddress' --output text)
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "API_URL = ${API_URL}"
-            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
-            cat frontend/.env
-      - run:
-          name: Deploy frontend objects
-          command: |
-            cd frontend
-            npm install --force
-            npm run build
-            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
-            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-      # - destroy_environment
-      # - revert-migrations
+#   deploy-frontend:
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - install_nodejs
+#       - run: sudo apt-get install tar gzip -y
+#       - restore_cache:
+#           keys: [frontend-build]
+#       - run:
+#           name: Get backend url
+#           command: |
+#             export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[].Instances[].PublicIpAddress' --output text)
+#             export API_URL="http://${BACKEND_IP}:3030"
+#             echo "API_URL = ${API_URL}"
+#             echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+#             cat frontend/.env
+#       - run:
+#           name: Deploy frontend objects
+#           command: |
+#             cd frontend
+#             npm install --force
+#             npm run build
+#             tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+#             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+#       # - destroy_environment
+#       # - revert-migrations
                     
-  deploy-backend:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - install_ansible
-      - add_ssh_keys:
-          fingerprints: ["a9:34:2a:d8:11:69:1c:e4:80:b5:d7:4b:e0:84:49:7f"]
-      - attach_workspace:
-          at: ~/
-      - restore_cache:
-          keys: [backend-deps]
-      - run:
-          name: Install dependencies
-          command: |
-            cd backend
-            npm install
-      - run:
-          name: Deploy backend
-          command: |
-            cd backend
-            npm run build
-            tar -czf artifact.tar.gz dist/* package*
-            cd ..
-            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
-      - run:
-          name: Deploy backend
-          command: |
-            export TYPEORM_MIGRATIONS_DIR=./migrations
-            export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
-            export TYPEORM_MIGRATIONS=./migrations/*.ts
+#   deploy-backend:
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - install_nodejs
+#       - install_ansible
+#       - add_ssh_keys:
+#           fingerprints: ["a9:34:2a:d8:11:69:1c:e4:80:b5:d7:4b:e0:84:49:7f"]
+#       - attach_workspace:
+#           at: ~/
+#       - restore_cache:
+#           keys: [backend-deps]
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             cd backend
+#             npm install
+#       - run:
+#           name: Deploy backend
+#           command: |
+#             cd backend
+#             npm run build
+#             tar -czf artifact.tar.gz dist/* package*
+#             cd ..
+#             cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
+#       - run:
+#           name: Deploy backend
+#           command: |
+#             export TYPEORM_MIGRATIONS_DIR=./migrations
+#             export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
+#             export TYPEORM_MIGRATIONS=./migrations/*.ts
             
-            cd .circleci/ansible
-            cat inventory.txt
-            ansible-playbook -i inventory.txt deploy-backend.yml
+#             cd .circleci/ansible
+#             cat inventory.txt
+#             ansible-playbook -i inventory.txt deploy-backend.yml
       # - destroy_environment
       # - revert-migrations
       # Here's where you will add some code to rollback on failure  
 
 #       # Here's where you will add some code to rollback on failure  
 
-  smoke-test:
-    docker:
-      - image: cimg/base:stable 
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Backend smoke test  # Install dependencies
-          command: |
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
-            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-            if curl -s $API_URL/api/status | grep "ok"
-            then
-              exit 1
-            else
-              exit 0
-            fi 
-      - run:
-          name: Frontend smoke test.
-          command: |
-            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
-            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
-            then
-              exit 0
-            else
-              exit 1
-            fi
-      # - destroy_environment
-      # - revert-migrations 
+#   smoke-test:
+#     docker:
+#       - image: cimg/base:stable 
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - install_nodejs
+#       - run:
+#           name: Backend smoke test  # Install dependencies
+#           command: |
+#             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+#               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+#               --query 'Reservations[*].Instances[*].PublicIpAddress' \
+#               --output text)
+#             export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+#             if curl -s $API_URL/api/status | grep "ok"
+#             then
+#               exit 1
+#             else
+#               exit 0
+#             fi 
+#       - run:
+#           name: Frontend smoke test.
+#           command: |
+#             FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+#             if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+#             then
+#               exit 0
+#             else
+#               exit 1
+#             fi
+#       # - destroy_environment
+#       # - revert-migrations 
+# #       # Here's where you will add some code to rollback on failure  
+
+
+#   cloudfront-update:
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - install_nodejs
+#       - run:
+#           name: Save Old Workflow ID to kvdb.io
+#           command: |
+#             export OLD_WORKFLOW_ID=$(aws cloudformation \
+#                       list-exports --query "Exports[?Name==\`WorkflowID\`].value" \
+#                       --no-paginate --output text)
+#             echo "Old Workflow ID: $OLD_WORKFLOW_ID"
+#             curl https://kvdb.io/7K8o6uZo6QoMYXeL9BabiR/old_workflow-id -d "${OLD_WORKFLOW_ID}"
+#       - run:
+#           name: Update cloudfront distribution
+#           command: |
+#             aws cloudformation deploy \
+#             --template-file .circleci/files/cloudfront.yml \
+#             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+#             --stack-name InitialStack
+#       - destroy_environment
+#       - revert-migrations  
 #       # Here's where you will add some code to rollback on failure  
 
-
-  cloudfront-update:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Save Old Workflow ID to kvdb.io
-          command: |
-            export OLD_WORKFLOW_ID=$(aws cloudformation \
-                      list-exports --query "Exports[?Name==\`WorkflowID\`].value" \
-                      --no-paginate --output text)
-            echo "Old Workflow ID: $OLD_WORKFLOW_ID"
-            curl https://kvdb.io/7K8o6uZo6QoMYXeL9BabiR/old_workflow-id -d "${OLD_WORKFLOW_ID}"
-      - run:
-          name: Update cloudfront distribution
-          command: |
-            aws cloudformation deploy \
-            --template-file .circleci/files/cloudfront.yml \
-            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-            --stack-name InitialStack
-      - destroy_environment
-      - revert-migrations  
-#       # Here's where you will add some code to rollback on failure  
-
-  cleanup:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Remove old stacks and files
-          command: |
-            export STACKS=($(aws cloudformation list-stacks \
-                --query "StackSummaries[*].StackName" \
-                --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
-            echo Stack names: "${STACKS[@]}"
-            export OldWorkflowID=$(curl --insecure https://kvdb.io/7K8o6uZo6QoMYXeL9BabiR/old_workflow_id)
-            echo Old Workflow ID: $OldWorkflowID
-            if [[ "${STACK[@]}" =~ "${OldWorkflowID}" ]]
-            then
-              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
-            fi            
+  # cleanup:
+  #   docker:
+  #     - image: cimg/base:stable
+  #   steps:
+  #     - checkout
+  #     - install_awscli
+  #     - install_nodejs
+  #     - run:
+  #         name: Remove old stacks and files
+  #         command: |
+  #           export STACKS=($(aws cloudformation list-stacks \
+  #               --query "StackSummaries[*].StackName" \
+  #               --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
+  #           echo Stack names: "${STACKS[@]}"
+  #           export OldWorkflowID=$(curl --insecure https://kvdb.io/7K8o6uZo6QoMYXeL9BabiR/old_workflow_id)
+  #           echo Old Workflow ID: $OldWorkflowID
+  #           if [[ "${STACK[@]}" =~ "${OldWorkflowID}" ]]
+  #           then
+  #             aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+  #             aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+  #             aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+  #           fi            
 
 workflows:
   default:
@@ -434,16 +429,16 @@ workflows:
           filters:
             branches:
               only: [master]
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
-      - run-migrations:
-          requires: [configure-infrastructure]
-      - deploy-frontend:
-          requires: [run-migrations]
-      - deploy-backend:
-          requires: [run-migrations]
-      - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
+      # - configure-infrastructure:
+      #     requires: [deploy-infrastructure]
+      # - run-migrations:
+      #     requires: [configure-infrastructure]
+      # - deploy-frontend:
+      #     requires: [run-migrations]
+      # - deploy-backend:
+      #     requires: [run-migrations]
+      # - smoke-test:
+      #     requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
